### ISSUE TITLE
Feature Request: Packing files

### ISSUE THREAD

**Issue by ghost** [SeriousCache/UABE#102]
This was mentioned in #95, but I wanted to bring it up again because I want a clear yes or no if this feature could come in the near future.

If this feature won't come, would it be possible for you to explain how packed files are formatted and how UABE unpacks packed files? I want to use this information to make my own tool dedicated just for packing files.

Thanks!

**Comment by 0x900x90** [comment]
I think you can use disunity for this. It works perfect with unityweb bundles. Also disunity is opensource, so you can check the code. Java code can be easily converted to C# for example.

**Comment by redlightnightlight** [comment]
Thanks for the link. Disunity has limited support for UnityFS, which is a file format introduced in Unity 5.x, but I will look into the code.

**Comment by DerPopo** [comment]
I've encountered some issues compressing bundles in the past (which is why there's an Unpack function in the API that doesn't work properly) but I'll take a look at it again since there's some demand for it.

**Comment by 0x900x90** [comment]
Also i found this python library.
https://github.com/hearthsim/unitypack

**Comment by DerPopo** [comment]
The next version will allow compression. LZ4 support is missing and I'll have to do some testing. I also still need to add it to the console commands.

**Comment by MagicDroidX** [comment]
I wonder whether there is any progress on this? :)

**Comment by DerPopo** [comment]
UABE 2.2 is out with compression support (LZMA only). Since it also fixes a bug writing assets metadata, it may work now even without compression.
