### ISSUE TITLE
batchexport command cannot unpack files including slashes in their names

### ISSUE THREAD

**Issue by 0x900x90** [SeriousCache/UABE#108]
UABE can't unpack some files in batch mode from assetbundles, when file name contains subpath.

For example:"GI\BuildPlayer-DesertDig Gameplay\73\73529832eff2e2de16e1420c061acdc7.pos"

You have to create subdirectories before unpacking them.

**Comment by 0x900x90** [comment]
Also sometimes export buttons do nothing, when i press them. Maybe it happens with unnamed assets only. I tried to export shader from unity 5.5.0p3 assets file. Export Raw started working only when i pressed Export Dump and cancelled. Maybe this happens on default name generation stage for filesave dialog. It's only my guess.

**Comment by DerPopo** [comment]
I'll keep an eye out for the file dialog bug, I haven't encountered it myself so far, even when forcing the legacy dialog.
