### ISSUE TITLE
Feature Request: Shader Extraction

### ISSUE THREAD

**Issue by erherhh4herh** [SeriousCache/UABE#112]
It would be nice to be able to extract .shaders from .assets files. They're supposed to be renamed txt files (that's the way they are in unity).

Please and thank you
- erherhh4herh

**Comment by nesrak1** [comment]
It's the m_Script if you export dump.

**Comment by DarkStarSword** [comment]
If you desperately want to extract shaders, use the unity_asset_extractor.py and extract_unityXX_shaders.py scripts in my 3d-fixes repository[1]. You won't get the original source code, but you will get the binaries as well as decompiled and disassembled versions using cmd_Decompiler[2] from 3DMigoto.

[1]: https://github.com/DarkStarSword/3d-fixes
[2]: https://github.com/bo3b/3Dmigoto/releases
