### ISSUE TITLE
Loading particle system crashes

### ISSUE THREAD

**Issue by nesrak1** [SeriousCache/UABE#121]
Any time I try to view data / export dump on a particlesystem in a 5.4 game crashes both api apps and gui. In a 5.5 game it works fine.

**Comment by DerPopo** [comment]
Probably it's an incompatibility with the 5.4.0f3 type database. Could you determine the exact version name as in the file header/TypeTree?

**Comment by nesrak1** [comment]
Its the latest version of 5.4f

**Comment by nesrak1** [comment]
5.4.5

**Comment by nesrak1** [comment]
Still not working on 5.6 game. Class appears to be missing several fields when compared with the TypeTree in a bundle exported from the editor.
[ParticleSystem.txt](https://github.com/DerPopo/UABE/files/1835431/ParticleSystem.txt)

**Comment by nesrak1** [comment]
I decided to write my own class exporter so I inserted a fixed version into the existing one for 5.6.
Before:
![assetbundleextractor_2018-03-31_11-41-04](https://user-images.githubusercontent.com/12544505/38165417-79b79f74-34d8-11e8-98f0-488b6ab3d7f6.png)
After:
![assetbundleextractor_2018-03-31_11-40-00](https://user-images.githubusercontent.com/12544505/38165413-736f805a-34d8-11e8-9d4d-0668f4afafc9.png)

[ParticleSysFix.zip](https://github.com/DerPopo/UABE/files/1865683/ParticleSysFix.zip)

**Comment by DerPopo** [comment]
Thanks for reporting back! It seems like this is one of the types that change regularly. For instance, the 2017.1.0f3 one has two additional bools (besides the changes of your type information file). I suspect the Unity version of the game you tested is newer than 5.6.0f3. 

Types can also differ between minor releases, and it'd take a lot of work to keep track of these changes. Binary pattern and debug symbol scanning may theoretically reduce the amount of work but certainly won't help with changes of the relevant engine code and structures (and I've seen such changes in almost every major release).

**Comment by nesrak1** [comment]
Looks to be so. I didn't realize the format changed during minor updates. This is on build 5.6.2f1.
