### ISSUE TITLE
MonoScript

### ISSUE THREAD

**Issue by OmegaRogue** [SeriousCache/UABE#126]
is there a plugin for exporting MonoScripts a file format thats usable in unity for them?

**Comment by OmegaRogue** [comment]
can i somehow let code export a MonoBehaviour as .dat from with dnSpy modified Game Code?

**Comment by DerPopo** [comment]
The next UABE version will allow to use type information from the game assemblies for MonoBehaviours.
I've created an external .NET tool that uses Mono.Cecil to extract this type information. UABE calls that tool if requested by the user and uses some pipe magic to gather the data directly through stdout.

It will allow to create full dumps of MonoBehaviour assets. Another feature I planned for the next release is json dump support. These can directly be used in Unity scripts with the UnityEngine.JsonUtility class.

To use the AssetsTools API from within the game code, you need to create (and use) a C++ (VS 2010) wrapper .dll. Feel free to ask questions on how to do that / using the API.

**Comment by OmegaRogue** [comment]
can you help me with creating a tool

**Comment by OmegaRogue** [comment]
Oder mit C++ und dem QT framework

**Comment by Bluscream** [comment]
Yes c# wrapper pls
