### ISSUE TITLE
Program crashes with certain files

### ISSUE THREAD

**Issue by Rocksnotch** [SeriousCache/UABE#135]
Hi! Been using the program to explore some files in a game and there are 3 files. Let's called them Decal1, Decal2, and Decal3. I can open 2 and 3, but 1 always crashes the program! Was wondering if I could get any help on this?

**Comment by DerPopo** [comment]
Could you upload the file it fails to open?

**Comment by Rocksnotch** [comment]
I would but technically the file is in a .assets file itself. I could upload the whole .assets file if you'd like.

**Comment by DerPopo** [comment]
Does it work with UABE 2.2?
