### ISSUE TITLE
Feature Request: Preserve folder structure on export

### ISSUE THREAD

**Issue by KiriSweets** [SeriousCache/UABE#137]
I downloaded this tool so I could look through a Unity game's sprites and it worked pretty fantastically for that. Then since it's a fairly unknown game I decided to try my hand at making sprite sheets for it since no one's done that yet. 

Now I've noticed that in the actual tool's UI it lists a folder structure for every file its found, but when using the export to PNG option for Texture2D files it just dumps everything into a single folder.
![capture_2017 07 02_16 03 43](https://user-images.githubusercontent.com/29843507/27773096-0f6b0dae-5f40-11e7-863d-f2c38ff712b3.png)

It would me immensely helpful for sorting purposes if the option to retain the folder structure when exporting files could be added.

Also, while it's not in my main interests, it's been noted to me that this program can't export standard font files (eg .ttf and .otf files that seem otherwise read as broken Texture2D files by the program).

**Comment by anubis71x** [comment]
Mine doesn't even show the path, other than the path ID. Is there anything I can do to get that info?
