### ISSUE TITLE
Adding new assets inside a bundle / updating resources list?

### ISSUE THREAD

**Issue by carpedee** [SeriousCache/UABE#164]
Hey, I just wanted to thank you for your explanations, now I'm starting to understand how the assets work inside a bundle.

I figured why my swapped mesh was invisible: the mesh I imported had actually a different skeleton: 3 additional bones, meaning 3 additional transforms and several additional gameobjects.
So I figured I would have to add the missing files inside my bundle with the file --> add function of UABE and update the skinnedmeshrenderer with the correct transform references.

But before that I made a simple test: without any other modification, I added a new texture inside my bundle (a texture coming from another bundle in the game).
Then I updated the reference in my material to link to this new texture inside my bundle. It doesn't load the texture once in the game, my character is white.

So I figured this new texture should also be added in a ressource list somewhere, otherwise the game won't load it?

I think I was mistaking assets for bundles. In my bundle there is an asset with an "assetBundle" type, which once exported as a dump file seems to contain the list of all the files in the said bundle. I guess I should update this one.

EDIT: My texture is still not loaded and I don't understand why. Could you get a glance at this txt file please?
The file I added is the last one in the m_preload (290) and the second one in the m_container (File ID: 6552088586798754424, named "test")
Did I miss something?
[AssetBundle_0_1.txt](https://github.com/DerPopo/UABE/files/1425204/AssetBundle_0_1.txt)

The texture I added was like that:
Name: test
File Id: 0
Path ID: 6552088586798754424
Mono ClassID: -1

I'm not sure I have to add an entry in the m_container part, especially since the one already present seems to encompass all the entries above (preload size = 291 once updated).
The issue is that this prefab file is a gameobject which only contains 12 transform references, so I don't see how it is linked to the 291 entries above...

**Comment by DerPopo** [comment]
Your AssetBundle entry does seem correct, though it should already be enough to refer to the texture through its Path ID if you don't have game code that searches for it by its AssetBundle or ResourceManager asset path. Did you set the class id to 0x1C for Texture2D in the Add dialog? Did you import the texture through the Edit plugin or through a raw import? A raw import should be the safest option (given both the source and the target file have the same Unity version) to make sure all texture parameters are the same.

The prefab GameObject probably is linked to more assets than these transforms. The transforms each have a m_Children list and m_Father and are all linked to different GameObjects, which in turn can have various components.

**Comment by carpedee** [comment]
I did set the correct classID for the texture (0x0000001C) and used the import raw function.
There must be a loading files list hardcoded somewhere. The issue definitely comes from the prefab which actually contains references to 12 files: some being transforms, some monoscripts and some other animations.
I would guess this prefab prevents the addition of the new elements but that's a while guess.  Could there be something concerning the bundle loading resources at runtime inside the Assembly-Csharp.dll or even inside the game.exe?

**Comment by DerPopo** [comment]
Unity might require all assets used by a prefab to be listed as a dependency in the AssetBundle asset.
UABE 2.2 shows this relationship more clearly with the additional Container column, and View->Containers shows all containers an asset belongs to since one asset could be a dependency of multiple containers/prefabs.
