### ISSUE TITLE
Any chance to get the shader export?

### ISSUE THREAD

**Issue by OkazakiNaoki** [SeriousCache/UABE#180]
Unity have their own way to serialize the 5.5 up shader code?
So probably there are no way to deserialize it?
Am I right?
I have some shaders really interested me.

**Comment by 0x900x90** [comment]
Shader code is packed using lz4 algo. How do you understand shaders code? It looks like assembler code for some variants or binary data for directX.

I can try to unpack them for you. If there are not too much of them.

**Comment by OkazakiNaoki** [comment]
But it's not readable.
I want to look into their CGPROGRAM.
Is it possible?

**Comment by OkazakiNaoki** [comment]
https://drive.google.com/file/d/1RQZNOalyb4xo02Lz9w9QBHpj4kTxlaPA/view?usp=sharing
Alright...the one named "shaders".
After you downloaded please let me know. I should deactivate the link.
And it's HLSL shader I think.

**Comment by 0x900x90** [comment]
Got it.
I think it's impossible to convert them into readable form. If you can find these shaders for another platforms, then you can try to do something with them.
