### ISSUE TITLE
Invalid file or unknown version?

### ISSUE THREAD

**Issue by ghost** [SeriousCache/UABE#181]
![image](https://user-images.githubusercontent.com/35980215/35599470-8cf25f00-0631-11e8-8e02-29076aac389e.png)
Hello, really need your help, when you open the file, an error occurs. I'm not the first one that You were interested in. But the guy brought the case to the end.

**Comment by danielfrausto** [comment]
Getting same error.

**Comment by DerPopo** [comment]
The files might be encrypted or of another file format. Could you send me a sample file?

**Comment by danielfrausto** [comment]
@DerPopo i suspect that the file is encrypted, i was able to unpack same file from a previous version. i believe the recent assets have been encrypted.

**Comment by DerPopo** [comment]
Hmm.. these files work just fine on my end.

**Comment by craziej2k** [comment]
I'm having the same issue with a different file. I'd post the file but it's 2.63GB
