### ISSUE TITLE
Сan't export bundles

### ISSUE THREAD

**Issue by kontrq** [SeriousCache/UABE#183]
In the archive there are 2 bundle files. One can be extracted, and the second one is cant be extracted (Invalid file or unknown version). Maybe you could find a way to extract from the second bundle file? Maybe its crypted?
[google drive](https://drive.google.com/open?id=1dpkhYAZOJZMJTrKMeNsT2uoistciggKp)
[virustotal](https://www.virustotal.com/ru/file/a2482e6573b87eca70704b7738bdf8b9c0d5ae42153cc58d7ed38584a84f6e85/analysis/)

**Comment by DerPopo** [comment]
The second file (2EDF...) contains seemingly random data, so it probably is encrypted.

**Comment by kontrq** [comment]
Is there a chance to find an encryption method? Perhaps somewhere in the application there is a hint? Could this be? For all encrypted files, the first hex string is the same.
