### ISSUE TITLE
Asset help.

### ISSUE THREAD

**Issue by InochiPM** [SeriousCache/UABE#185]
Hello! I have been using this program for a bit now and i noticed there isnt a way to make things transparent in the program. 

What i mean is i have this texture here. 
![dialog_areyousurejp](https://user-images.githubusercontent.com/13459080/35905221-47d227c4-0bb4-11e8-9763-84bb97f990ac.png)

And when i go to edit the original file shown here (even though its different but thats not the point lmao )
![dialog_delete_jp-sharedassets0 assets-26](https://user-images.githubusercontent.com/13459080/35905319-9ee4292c-0bb4-11e8-8f4a-030203141282.png)
 What i end up in the game with is a non-transparent background on the first image, and no matter how much i play with the settings in edit it does nothing at all!

**Comment by carpedee** [comment]
Are you using a format which supports an alpha channel for importing your texture, like DXT5? Also, many materials don't support transparency for diffuse maps so you may want to check it out

**Comment by InochiPM** [comment]
@carpedee I tried that format and i also tried ARGB32 and it still didn't show up right, the transparency was all white.
