### ISSUE TITLE
Invalid file or unknown version?

### ISSUE THREAD

**Issue by hentei009** [SeriousCache/UABE#207]
![image](https://user-images.githubusercontent.com/39165912/39881204-df93ff0e-5445-11e8-92d9-2c9d4f5549c3.png)
I try to open a Kirara Fantasia file and this error message appears
I leave you the link of the files
https://www.dropbox.com/sh/sbv5hjmjtq20bbi/AAATFRdCirENOXlg4hc2vQGWa?dl=0

**Comment by 0x900x90** [comment]
I have only one question. Why you decided that it's a bundle file?

**Comment by hentei009** [comment]
the other files if I can open them, but since March I was not allowed to open them
![image](https://user-images.githubusercontent.com/39165912/40089595-16557344-5872-11e8-8b0a-e1f90f027978.png)

**Comment by 0x900x90** [comment]
I think game developers decided to encode/encrypt files from march release or something else happened. Files you uploaded are not bundles.

**Comment by hentei009** [comment]
some method to decrypt or decode these files? would be very helpful, I just want the renders, for that I use this tool
