### ISSUE TITLE
Importing custom shaders?

### ISSUE THREAD

**Issue by carpedee** [SeriousCache/UABE#217]
I'm not sure if it can be done with UABE but I have some custom shaders created in Unity, I was thinking about importing them in a game (made with the same version of Unity). So basically extracting those from my already built assets as dump files, correcting the different links between shaders and materials to work in the game, and importing them into the game assets. It actually works except the shaders don't behave as expected. I notably created some custom shaders to better handle transparency with several passes. Now I wonder if I overlooked something? It may just be impossible

**Comment by 0x900x90** [comment]
Never tried to change shaders to the completely new. But i think that this should be possible.

**Comment by DerPopo** [comment]
Are there any differences between the original exported raw shader and dump export->import->raw export? There may be some discrepancies between the type information embedded in UABE and the actual format since minor Unity updates already can change the format.

I should definitely take a look at the Shader format, the difficulty being that it has changed 3 or 4 times.

**Comment by carpedee** [comment]
I can confirm that the dump import/export process is lossless in this case. I compared both raw files with an Hex editor and there is absolutely no difference.

Indeed, shaders structures have changed drastically with the newer Unity versions.

But what surprises me is that an incorrect structure in the shader should result in something visually very wrong or even a crash. Here I'm pretty sure the shader is read correctly, the result being displayed on screen being anything but random. It kinda works as it should but not exactly, a bit like if the passes were not sorted in the correct order. Weird. To be honest the only shader I managed to make work as expected is the standard shader!

**Comment by thejeffreyallen** [comment]
I use custom shaders all the time. first, in visual studio, you need to make sure that the Fallback "Diffuse" line at the bottom is removed as this will point to an invalid fileID and pathID for the unity standard shader. Then, simply export as raw, import as raw.
