### ISSUE TITLE
Is there a way to extract / import monoscript files?

### ISSUE THREAD

**Issue by dretax** [SeriousCache/UABE#219]
I recently came to a game which compiled all their dlls to an assetbundle, thats why i am asking.

**Comment by DerPopo** [comment]
MonoScript assets are just references to external .dlls, which may also be located inside the bundle. In that case, they should appear inside the drop-down list of the UABE main window. Desktop games usually have these files inside the <game>_Data/Managed folder.

**Comment by dretax** [comment]
They indeed appear, but cannot export them.

**Comment by Kalle801** [comment]
Would be a great feature!

**Comment by AndreiGTA** [comment]
How extract monoscript in uabea?
