### ISSUE TITLE
skel file exported can not reimport to Unity

### ISSUE THREAD

**Issue by Casanova1986** [SeriousCache/UABE#224]
After I export .skel file and .json file. it can not be import to unity.

EndOfStreamException: Failed to read past end of stream.
Spine.SkeletonBinary.ReadFully (System.IO.Stream input, System.Byte[] buffer, Int32 offset, Int32 length) (at Assets/Spine/spine-csharp/SkeletonBinary.cs:882)

**Comment by LHS1998** [comment]
How to export as .skel files? I used export raw but it doesn't work
