### ISSUE TITLE
How to open ClassDatabasePackage

### ISSUE THREAD

**Issue by dmc31a42** [SeriousCache/UABE#229]
Hello, UABE is always useful tool for me.
I wonder how to open ClassDatabasePackage (*.tpk).
In #58 (https://7daystodie.com/forums/showthread.php?22675-Unity-Assets-Bundle-Extractor/page8&p=459961#post459961), It is mentioned about how to open in API. But, I could find. I use 2.2beta3 API.

**Comment by DerPopo** [comment]
ClassDatabasePackage currently is not included in the API. I'll change that for the next release, but in the meantime you can export the class database through UABE (Options -> Edit Type Package).

**Comment by dmc31a42** [comment]
One more thing, the names of ClassDatabase item in tpk are mismatched to actual version. Like, in U5.5.0f2 actual cover 3.5.0f1 and 3.5.* and U2018.1.1f1 cover 2017.4.8f1 and 2017.4.*.
Please check.
