### ISSUE TITLE
MonoBehaviour - Unpredictable Sort

### ISSUE THREAD

**Issue by JeslynMcKenzie** [SeriousCache/UABE#232]
When attempting to sort by "Type", MonoBehaviour's with nested classes do not sort properly.

Example Results

MonoBehaviour : Inventory.Items.Accessories
MonoBehaviour : Inventory.Items.Accessories
MonoBehaviour : Inventory.Items.Armors <------ Not sure why this is here!
MonoBehaviour : Inventory.Items.Accessories
MonoBehaviour : Inventory.Items.Accessories

**Comment by DerPopo** [comment]
It's a simple buffer size issue (the internal type name is stored by its first 27 characters only). I'll increase the buffer size for the next release.

**Comment by JeslynMcKenzie** [comment]
>It's a simple buffer size issue (the internal type name is stored by its first 27 characters only). I'll increase the buffer size for the next release.

@DerPopo Sounds good! Do you by chance have something setup for donations? You’ve put a lot of work into this and I’d like to donate if you do.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DerPopo** [comment]
Thanks for the offer!
I may look into adding a donate option in the future, such as through bitcoin (or others).
