### ISSUE TITLE
Export Models with Material/Texture Data

### ISSUE THREAD

**Issue by wertercatt** [SeriousCache/UABE#244]
Currently, I can export both the texture and the model for an asset, but the exporter doesn't provide any information in the exported model files for how the texture should be applied. (I tested both .dae and .obj export for this.)

See attached archive
[auntArctic_mesh.zip](https://github.com/DerPopo/UABE/files/2603951/auntArctic_mesh.zip)

**Comment by DerPopo** [comment]
There are texture u/v coordinates in both the obj and dae files.
The obj file has lines starting with "vt" , the dae file has
```<input offset="0" semantic="TEXCOORD" source="#meshId0-tex0" set="0" />```
assigned to the mesh, along with the meshId0-tex0 array.

**Comment by wertercatt** [comment]
It's not clear how to tell the modeling program to use the proper texture, however. And it also doesn't tell the user what the proper texture is within the export.
