### ISSUE TITLE
Feature: Edit Audio

### ISSUE THREAD

**Issue by xp4xbox** [SeriousCache/UABE#246]
It would be very useful if there was a plugin to edit the audio like there is for textures.

**Comment by jack980517** [comment]
#91

**Comment by xp4xbox** [comment]
Still would be very useful. That method is cumbersome,

**Comment by xp4xbox** [comment]
@DerPopo I think it would be nice if you could add the source code on github. So others can contribute.

**Comment by jack980517** [comment]
* Install Unity Editor. Make sure you use the same version that was used to build the asset file you want to modify.
* Import the modified audio file into your project.
* With the audio file selected in the editor, open the drop-down menu in the bottom-right corner, create an asset bundle with any name, and select it. That would include this audio file in an asset bundle.
* Copy the code for building asset bundles from [this official manual page](https://docs.unity3d.com/550/Documentation/Manual/BuildingAssetBundles.html), and use the newly appeared menu item to build the asset bundle.
* If the original asset bundle (not the one you've built) only contains a single audio file:
    * Replace its `.resource` file with yours.
    * Use UABE to edit the AudioClip asset in the original asset bundle, and change the size value to the size of the new `.resource` file. (The offset should be 0 in both files.)
* If not (note that I haven't tested this second case, and all this is just speculation that should work in theory):
    * Append the contents of your `.resource` file to the original one with a hex editor or the following command: `copy /b original.resource+your.resource new.resource` (Backup original.resource and rename new.resource to original.resource obviously) This method wastes disk space since it leaves the original audio data in the `.resource` file unused, but replacing the original data would be way more cumbersome.
    * Use UABE to edit the AudioClip asset in the original asset bundle. Change the offset value to the original size of the `.resource` file (i.e. before you appended the data), and the size value to the size of the `.resource` file you've built.
* Done. It should work now.

**Comment by Arfra-token** [comment]
@jack980517 Hi,guy.I also encountered the problem of modifying the AudioClip file.If the original asset bundle contains not only one audio file,is there any possible way to modify a particular AudioClip file?

**Comment by DerPopo** [comment]
@Arfra-token I think the manual jack980517 provided should cover it. Generate a .resource file with the new audio through Unity Editor, append it to the original .resource file and fix the original AudioClip (the one you want to modify) by updating the offset and size values (using the unmodified .resource file size in bytes as the offset and the size of your own .resource file from Unity Editor in bytes as the size).

**Comment by Arfra-token** [comment]
@DerPopo Thanks a lot! That's quite useful. According to the steps you provided, I have successfully modified the audio I want.
Besides,is it possible to modify an audio file just like a Texture2D file,which don't have to add additional . resource files?It would be much more convenient if everything can be packed into a . exe file.
Looking forward to your reply.
