### ISSUE TITLE
Multiple dump import

### ISSUE THREAD

**Issue by Vooker525** [SeriousCache/UABE#248]
Is there a way to import multiple dump files at once? I have around 100 files and its hard to input them manually. Cannon use installer package file because PathID always different

![screenshot_392](https://user-images.githubusercontent.com/5042845/49350041-6c89f600-f6be-11e8-8734-89923b79642a.png)

**Comment by wchristian** [comment]
No idea if UABE can do it, but if you google for "UnityEx" by DragonZH, that tool has a command line mode that can import in batch if you prepare the correct directory structure.

**Comment by Vooker525** [comment]
Thats another problem. UABE exports raw files without proper names and i dont know how to rename them properly. Raw files have name inside but i dont know a script that would take the string inside file and rename it with that string

**Comment by Vooker525** [comment]
Also i dont know how to transform Dump files to Raw without using UAEB

**Comment by Vooker525** [comment]
Is it possible to match files only by name?

**Comment by Vooker525** [comment]
Yea, i figured that out. I want to modify Audio files from other game. So i make my own .asset and .resource via Unity engine. Then export dump data from it. And the problem is that UABE will automatically match files only if i import in the same .asset, not others. For importing to other .assets i either have to rename dump file to match new .asset file, its ID in that file and type of file or import them manually by hand each. I found a tricky solution where i export dump files from asset which i want to modify, then select those i want to be changed, put them in separate folder, export dump files from asset i created to another separate folder and batch rename them via powershell utility. I really want to see import feature like it is done in UnityEX where all files stored in separate folders. For example texture1.tex is in sharedassets0\Textures\res_sharedassets0; texture65.tex is in sharedassets8\Textures\res_sharedassets8 and so on. This allows to export and import by name without all that stuff i described above

**Comment by thejeffreyallen** [comment]
I made a python script for batch renaming dumps just for this very issue if you're interested. You'll need to edit it to add your own file path and starting pathID for it to work properly. 
httpsrive.google.com/file/d/1qNTr3dR5RXtChSzlfpu0pcXRdDQuowGX/view?usp=drivesdk

**Comment by Phoney-X** [comment]
> I made a python script for batch renaming dumps just for this very issue if you're interested. You'll need to edit it to add your own file path and starting pathID for it to work properly. 

The file does not exist.
