### ISSUE TITLE
Getting midi files exported correctly?

### ISSUE THREAD

**Issue by punctdan** [SeriousCache/UABE#261]
Hi, whenever I try to export a .mid extension file in any method given by UABE, it doesn't get exported without lossless. I want it to be possible to export .mid files from asset bundles. Thanks.

**Comment by DerPopo** [comment]
I'll assume the files are in AudioClip assets, linked to a streamed data file.
I haven't looked into the chamber of dark magic of FMOD sound banks so far, so I'm actually using the official FMOD API to decode the sounds to raw PCM data. Usually, you'll get exactly the same sound and sound quality as with normal playback - which doesn't apply to midi files, obviously.  

If you click View Data on the asset, you can see where the sound data is stored (file name, byte size, offset). The plugin does not have an option to export the original .fsb file, so you have to export it manually with a hex editor (such as HxD). You may want to take a look at [fsbext](http://aluigi.altervista.org/search.php?src=fsbext) and [python-fsb5](https://github.com/HearthSim/python-fsb5) to export the sound in its original format but these tools don't say anything about midi export so you may get unusable files.

**Comment by jack980517** [comment]
I doubt this would have anything to do with streamed data files. Midi files are like sheet music; they define what instruments are to be used and what notes are to be played. Therefore they're usually less than 200KB or even 100KB, and wouldn't need to be put in the streamed data file. It also has nothing to do with PCM. I googled a bit and didn't find any information about fsb files containing midi files; what I did find is using fsb files as "instruments" for playing midi files with the FMOD API, which is probably unrelated to the use case here.

**Comment by punctdan** [comment]
> I doubt this would have anything to do with streamed data files. Midi files are like sheet music; they define what instruments are to be used and what notes are to be played. Therefore they're usually less than 200KB or even 100KB, and wouldn't need to be put in the streamed data file. It also has nothing to do with PCM. I googled a bit and didn't find any information about fsb files containing midi files; what I did find is using fsb files as "instruments" for playing midi files with the FMOD API, which is probably unrelated to the use case here.

That's right jack980517. I'm trying to get midi files to discover where the sounds are played in a track, midis don't store the sounds but their placement in the track. The ones I have take up less than 100KB as you said.
