### ISSUE TITLE
Has anyone made a plugin for Importing fonts? Or knows other font editing methods?

### ISSUE THREAD

**Issue by StarvinArtist** [SeriousCache/UABE#286]
(Forgive me, I'm not really smart)
I use UABE quite frequently, it is an amazing program. I have been working to try and prepare a game for translation. In order to do that, I need to replace a font with a custom one, since the game outright refuses to read/display any Non-English letters. The font is nearly the same but just changes some characters to display Latin letters, keeping the same underlying character value (^ = ñ , @ = á , etc). I understand that Mr.Popo is busy working on other features, but has anyone here developed a font import plugin? Or know a different program that does? Or even knows another method I can use (like hex editing) to achieve a similar result to what I'm looking for?
Thank you and have a wonderful day.

**Comment by qq1710301281** [comment]
我也想知道怎么办，好多字体中文都不能显示呢 所以通过十六进制将想改的字符改成ASCII也没办法-0-

**Comment by GreatTomy** [comment]
Did you found something? I need it too.
And: to what language do you translate?
