### ISSUE TITLE
"Unable To Open Streamed Data File!" & "Unable To Convert The Texture Data!

### ISSUE THREAD

**Issue by Isaaaaaaaaaaaaac** [SeriousCache/UABE#300]
When i try to extract "Texture2D" and "AudioClip" it just brings me up a error that says "Unable To Open Streamed Data File!" And "Unable To Convert The Texture Data!

**Comment by dt192** [comment]
I also have this issue.

**Comment by feightwywx** [comment]
I have this issue partly...I can extract "Texture2D",but when it goes to "AudioClip",I got "Unable To Open Streamed Data File!".

**Comment by symbol54** [comment]
i have same problem
