### ISSUE TITLE
data formats???

### ISSUE THREAD

**Issue by Brian151** [SeriousCache/UABE#301]
There are a few of the data formats from which all assets/components are comprised which have caused me some confusion because of me not seeming to have any assets where they're in use.
[or at least, knowing of any] so, the information window and/or dump files can't help me to understand them.

namely, set and vector

so, care to explain, or point me in the direction of something that explains all the "basic" data types in use by the format? 

i found one example of set, and in this example, it's just an array of integers

don't think i've found any vectors yet...

**Comment by DerPopo** [comment]
(Serialized) Assets consist of elementary data types, namely 8,16,32,64 bit signed/unsigned ints, floats, doubles and arrays. Everything else is composed of these types, including set, vector, map and string.
If you want to take a look at UABE's type information, use Options->Edit Type Package, open classdata.tpk, export an entry and open it through Options->Edit Type Database.
The align checkbox means that if the file offset after the element is not a multiple of 4, it will add null bytes as padding.

**Comment by Brian151** [comment]
sorry for such delays replying to this comment
i'm not so much interested in editing the type database as reading it, so that's on the list for when/if i continue messing with this format... 

in any case, thanks for explaining that
