### ISSUE TITLE
How to extract PNG from Texture2D assets via command line?

### ISSUE THREAD

**Issue by Cynthion** [SeriousCache/UABE#305]
Dear DerPopo

Thanks a lot for your big efforts you put into the UABE tool! I'm really new into game modding and Unity assets, so let me apologize for the upcoming question :-)

I wonder if I can use the command line tool to simply extract a Texture2D file within an asset to PNG by providing the asset path and an output path. I read through all of the Readme.txt file, however, I didn't quite understand if the asked is possible with UABE command line. If not, would you have a suggestion on how to achieve this? The files I'm interested in seem to be compressed with DXT1, if that is of any help...

Any help or hint is very much appreciated, thank you very much!

**Comment by Jordan9232** [comment]
I am also wondering the same thing. I initially thought about using the API but I was hoping to use it with C#, I am not familiar with C++. Command line would be the easiest option for what I'm doing
