### ISSUE TITLE
Something wrong happens while opening assets file.

### ISSUE THREAD

**Issue by 0x900x90** [SeriousCache/UABE#306]
UABE can't process this file. I think the problem is inside AssetBundle asset type inside this file.
https://yadi.sk/d/Ql9VeLrNPpTeEw

**Comment by DerPopo** [comment]
There appears to be a huge dependency overlap in the AssetBundle asset. UABE tries to map all assets to the container names (by index) while loading the file, which obviously is a bad idea for that bundle.

**Comment by 0x900x90** [comment]
I tried to convert AssetBundle 2018.x to 5.x. I couldn't open original bundle, but i had no problem with opening new one. When i converted AssetBundle asset from 2018 to 5.4 i got the same problem with new assetbundle. Therefore, I thought that the problem is in AssetBundle type.

So, we can close this issue, or you going to fix it? I know how to avoid this problem in future if deal with such bundles in future.

**Comment by DerPopo** [comment]
The UI rework I'm currently doing requires some fundamental changes anyway, so I have already worked out (and implemented) how to deal with it properly. I'd keep this issue open until the next release (or forget about it and maybe close it a few years later).
