### ISSUE TITLE
Texture Error for Contra Return

### ISSUE THREAD

**Issue by Contra6** [SeriousCache/UABE#310]
Hi decided to try your program, but throws error. Can you fix it?.
Download [Texture Error](https://yadi.sk/d/lItXj9Zkz19k6A)
I don't know who else to turn to for help. Thanks

**Comment by 0x900x90** [comment]
Похоже использована какая-то защита от распаковки. Это не проблема UABE.

I think custom protection has been used on this texture2D assets.

**Comment by Contra6** [comment]
Ну так что возможно его исправить? Мне всего то не хватает половина текстурков, все больше нечего. Это уже 3 форум обращаюсь на помощь)

**Comment by 0x900x90** [comment]
Исправлять нечего. Если надо достать текстуры, то придется смотреть код самой игры.
Что за игра?

**Comment by Contra6** [comment]
Так и называется Garena Contra: Return для Android
Я специально выложил ссылку для [текстурку](https://yadi.sk/d/lItXj9Zkz19k6A), блин одно огорчение :( Неужели никто не поможет?

**Comment by Contra6** [comment]
Hello??

**Comment by 0x900x90** [comment]
Я тебе уже ответил. UABE и другие программы могут только извлекать стандартные текстуры.
В твоей игре текстуры накрыты какой-то защитой. Исполняемые файлы игры тоже зашифрованы или закодированы. Здесь тебе никто помочь не сможет.
Если хочешь извлечь текстуры, изучай взлом приложений. Конкретно в этом случае надо дампить память приложения, искать Assembly-CSharp.dll. Потом изучать код и расшифровывать текстуры. Можешь поискать единомышленников на 4pda.

**Comment by Contra6** [comment]
Понятно, спасибо. Нет так нет, спросить стоило. Такую проблему я с 1-ой сталкиваюсь, и никто не может его решить. Я в шоке...
