### ISSUE TITLE
Unityweb file support

### ISSUE THREAD

**Issue by AndnixSH** [SeriousCache/UABE#312]
Can you add support for .unityweb files?
I want to be able to extract global-metadata.dat from it

[web.data.zip](https://github.com/DerPopo/UABE/files/3994978/web.data.zip)

**Comment by 0x900x90** [comment]
You can use this if you want. It's simple commandline app.

[WDU.zip](https://github.com/DerPopo/UABE/files/3998240/WDU.zip)

If somebody needs source codes, it's Net app and i've not used any obfuscators. If you understand what i mean :)

**Comment by AndnixSH** [comment]
Thanks it worked

Yeah I know how to see source code hehe. This source code might be helpful for UABE developer

**Comment by ahmadhossiny** [comment]
> You can use this if you want. It's simple commandline app.
> 
> [WDU.zip](https://github.com/DerPopo/UABE/files/3998240/WDU.zip)
> 
> If somebody needs source codes, it's Net app and i've not used any obfuscators. If you understand what i mean :)



> You can use this if you want. It's simple commandline app.
> 
> [WDU.zip](https://github.com/DerPopo/UABE/files/3998240/WDU.zip)
> 
> If somebody needs source codes, it's Net app and i've not used any obfuscators. If you understand what i mean :)

Hello
How can we convert the folder created by WDU to a .unityweb format file?

**Comment by ahmadhossiny** [comment]
> You can use this if you want. It's simple commandline app.
> 
> [WDU.zip](https://github.com/DerPopo/UABE/files/3998240/WDU.zip)
> 
> If somebody needs source codes, it's Net app and i've not used any obfuscators. If you understand what i mean :)

Hello
How can we convert the folder created by WDU to a .unityweb format file?

**Comment by JonJon565** [comment]
@0x900x90 how did you make the scripts?

**Comment by JonJon565** [comment]
also do you have one for brotli?

**Comment by JonJon565** [comment]
[UCCB.zip](https://github.com/SeriousCache/UABE/files/13062466/UCCB.zip)
this is also a CLI app, its used for is converting a UnityWeb Compressed Content (brotli) Header file (such as the ones yandex.com) sometimes uses into a UnityWebData1.0 Header file that @0x900x90 wdu.exe CLI app can process
command
uccb.exe -d -i "input_file" -o "output_file"
