### ISSUE TITLE
Unknown Texture2D Asset Format

### ISSUE THREAD

**Issue by ZapTech43** [SeriousCache/UABE#315]
When i was exporting Texture (.tga) Files from the Call Of Duty : Mobile .obb file the error occurs.

Maybe they are using the newest Unity or other tool? I have no idea if they are using other tools or a new unity OR they use an encryption method? because the size of the texture are really small it is not more than 1mb.

This is the asset file :
https://drive.google.com/file/d/18JppUlARAMS2fhb-64dvIlz0VzG4sH5x/view?usp=drivesdk

It seems that i have to export the .resS file from the RAW assets file, but i can't open it with UABE

This is the RAW (un-exported) asset file : 
https://drive.google.com/file/d/18I-EAQoYy1Onfu1z764OxaWe8GJSRapR/view?usp=drivesdk

**Comment by AJMK418** [comment]
I m also doing the same thing but getting error when exporting the Texture2D file...
