### ISSUE TITLE
UABE wont open certain compressed asset files

### ISSUE THREAD

**Issue by York2016** [SeriousCache/UABE#336]
Hi, 
im trying to open these files (they're .assets but without any file extension and compressed) but i only get the error "Unable to read the bundle file! (Invalid File or Unknown version?)"
I know they can be opened since in previous versions of the game they could be opened with UABE and then decompressed. I'm not sure if this is because of something on UABE's end or some form of obfuscation by the devs to prevent modding (BSG: Deadlock). 
Its weird because the assets files in the BSG_Data folder can be easily opened but the StreamingAssets assets cannot.

**Comment by NBAPJ** [comment]
Having the same problem opening files in the StreamingAssets folder.  Did any ever solve the problem
