### ISSUE TITLE
Looking for Unity 2019 4.4 support

### ISSUE THREAD

**Issue by sharkfin18** [SeriousCache/UABE#351]
Just 2 months and Unity has already updated so frequently... 
If there is a classdata with 2019.4.4x it would be much appreciated.

**Comment by ChenLauter** [comment]
It would be much appreciated

**Comment by ChenLauter** [comment]
+1

**Comment by Tantalus-X** [comment]
me too and for Unity 2020.1.0

**Comment by SNRB** [comment]
+1 

I too hope it will get an update for new version, or at least latest 2019 versions.
