### ISSUE TITLE
Replacing FSB5 audio in .resource without losing storage 

### ISSUE THREAD

**Issue by Swagsy** [SeriousCache/UABE#353]
Would it be possible to use an Hex Editor and replace the audio that way? If you create a new .resource bundle and reference it in the m_Source strings of the AudioClip dumps you're just wasting space with the old, no longer used audio in it. Besides that, doesn't the .resource file only store raw audio or does it have other assets as well?

**Comment by jack980517** [comment]
the .resource file is just one or more fsb files joined together. the position (offset) and size (length) of each fsb file is specified in the unity asset files that reference the resource file.

> If you create a new .resource bundle and reference it in the m_Source strings of the AudioClip dumps you're just wasting space with the old, no longer used audio in it.
not sure not you mean here. if you create a new .resource file and update the m_Source reference, the old .resource file is no longer being used, and you can safely delete it, so there's no wasted space.

when you generate a new fsb file, you can choose to append it to the existing .resource file (which would result in the old .fsb file wasting space, lying unused), or you can choose to remove the old fsb file data to save space (but you would need to update the reference for all other fsb files in the .resource file that comes after what you removed).

**Comment by Swagsy** [comment]
Yeah that's what I meant, I'm trying to modify tens of audio files in one game, but not all of the audio (Which is a lot), so I'll have to append the new audio to the .resource file and remove the old one. Would I have to delete the old fsb file data with a Hex Editor then?

**Comment by jack980517** [comment]
>  ... so I'll have to ... remove the old one. 

> Would I have to delete the old fsb file data

Why are you saying something and then immediately asking the same thing lmao

**Comment by jack980517** [comment]
>  ... so I'll have to ... remove the old one. 

> Would I have to delete the old fsb file data

Why are you saying something and then immediately asking the same thing lmao
