### ISSUE TITLE
Error "This file isn't a valid assets file!" - StandaloneWindows64

### ISSUE THREAD

**Issue by TheMegax** [SeriousCache/UABE#362]
Asset Studio GUI works on that file, but UABE doesn't seem to work at all.
Using Unity 2019.4.4 (I know this tool hasn't been updated for that version, but that is an error that I haven't encountered before)
EDIT: Apparently UABE can't open bundle files in StandaloneWindows64 format, as it can open StandaloneWindows just fine

**Comment by DirtDogg101** [comment]
iv had the same issue! with 2019.3.6f1

 go to open info and it gives me that it is not a valid asset file, and the assets don't export correctly

**Comment by NBAPJ** [comment]
Was this issue ever fixed

**Comment by BoomBookTR** [comment]
![image](https://user-images.githubusercontent.com/10184695/106377125-cc1de200-63ab-11eb-9c7c-b41a0c9f5600.png)

[locale.zip](https://github.com/DerPopo/UABE/files/5899312/locale.zip)

**Comment by RatMann** [comment]
Sorry for necroing but has anyone found a solution yet?
