### ISSUE TITLE
An error when trying to open bundle (plz fix)

### ISSUE THREAD

**Issue by EnumInt** [SeriousCache/UABE#366]
When I try to open the resource.asset file it tells me Unable to read bundle file! (invalid file or unknown version?)

**Comment by asdfghjklqwertyuiop1234** [comment]
same

**Comment by d1ddle** [comment]
If you're trying to edit Among Us, it is the `sharedassets7.assets` file you need to open. Not the `resource.assets`.

If you're trying to edit a different game, I'm sorry can't help ¯\_(ツ)_/¯

**Comment by Igor55x** [comment]
Hi. `resource.asset` **isn't a bundle file**. Bundles usually have the extension `.unity3d` and always the header "UnityFS".
Maybe you confused the `.asset` extension with `.assets`.
`.assets` files can be opened with UABE without problem.
`.asset` files can be opened with Unity. Just import the `resource.asset` file into Unity.
**Also, you can always look on the Internet for guides on how to do this.**
