### ISSUE TITLE
I can't change the Hats texture in Among Us

### ISSUE THREAD

**Issue by Jazzox** [SeriousCache/UABE#373]
when i try to export the texture as a .png, it shows me these two errors 
![image](https://user-images.githubusercontent.com/73591607/97433687-f2f0f600-192e-11eb-96e7-067d8943a90f.png)
![image](https://user-images.githubusercontent.com/73591607/97433702-fab09a80-192e-11eb-881d-471c8ddbba02.png)
how can I fix this?

**Comment by d1ddle** [comment]
You must export all Texture2D objects from the `sharedassets7.assets` , as .pngs, into a folder and then you can edit them.
Once edited, select your `sharedassets0.assets` and re-import the textures using the program.
`File>Open>Sharedassets7.assets>U2019.2.0f1>`Select all Texture2D Objects (From Consolas0 -> Temp)`>Plugins>ExportTo.Png`

**Comment by Robotnic25** [comment]
The problem is, and I'm assuming they're having the same problem, specific texture assets throw up that error when you try and export them. I am running into the same problem and can not figure how to fix it.
