### ISSUE TITLE
MSVCP100.dll not found error

### ISSUE THREAD

**Issue by 6zd** [SeriousCache/UABE#374]
I keep getting an error saying: "The code execution cannot proceed because MSVCP100.dll was not found. reinstalling the program may fix this problem." when i try to run the program (it is unzipped and extracted properly), ive installed both 64 bit and 32 bit for 4 different versions it still wont work please help!
![Screenshot (3)](https://user-images.githubusercontent.com/73720662/97755566-cc1df580-1acf-11eb-9cc5-9addda640fef.png)

**Comment by DarkAshe** [comment]
I have the same error

**Comment by 007-Tommy** [comment]
Same error too

**Comment by Spinderman** [comment]
i fixed this by installing [Microsoft Visual c++ 2010](https://www.microsoft.com/en-us/download/details.aspx?id=26999)
