### ISSUE TITLE
PlayerSettings - Extracting

### ISSUE THREAD

**Issue by DragonTTK** [SeriousCache/UABE#395]
Is it possible to export the dump of PlayerSettings from globalgamemanagers? Because i've tried doing it with my own unity project and other unity based games but cant seem to get it working.

![error](https://user-images.githubusercontent.com/20360643/105578226-867a6d00-5d4c-11eb-8e9b-d0e34970ba05.png)

**Comment by Igor55x** [comment]
DragonTTK, this isn't possible because the type database does not support PlayerSettings from globalgamemanagers whose version is higher than 2019.2.0f1

**Comment by DragonTTK** [comment]
> DragonTTK, this isn't possible because the type database does not support `PlayerSettings` from globalgamemanagers whose version is higher than `2019.2.0f1`, but you can try manually although it is rather difficult.
> **Please send me the globalgamemanagers file, maybe I can help with this.**

Alright ill see about sending you it currently i am using this version of unity Unity 2018.4.28f1

**Comment by Igor55x** [comment]
I tried to manually rewrite the dump file from globalgamemanagers file. Here's the dump: [link](https://drive.google.com/u/0/uc?id=1pQcxxMqd7Gb4lOlYNx4bg0NUKnCWUuzt&export=download).
But this dump may not contain some fields because I couldn't get them.
**When you finish editing the dump file, send it to me. Then I will modify globalgamemanagers and send it to you.**

**Comment by nesrak1** [comment]
Try to see if this will work. It's made for `2018.4.10f1` so it could be outdated but it's worth a shot. https://github.com/nesrak1/AssetsTools.NET/files/5139741/classdata-U2018.4.10f1.zip (replace the classdata.tpk file by uabe with the one from that zip, ignore the classdata-uabe.tpk file)

**Comment by DragonTTK** [comment]
> I manually rewrote the dump file from globalgamemanagers. Here's the dump: [link](https://drive.google.com/u/0/uc?id=1pQcxxMqd7Gb4lOlYNx4bg0NUKnCWUuzt&export=download).
> But this dump may not contain some fields because I couldn't get them.
> **When you finish editing the dump file, send it to me. Then I will modify globalgamemanagers and send it to you.**

Thank you for the help i was mainly looking for the option "Allow unsafe code" as i am trying to see if its possible to load a custom DLL.

> Try to see if this will work. It's made for `2018.4.10f1` so it could be outdated but it's worth a shot. https://github.com/nesrak1/AssetsTools.NET/files/5139741/classdata-U2018.4.10f1.zip (replace the classdata.tpk file by uabe with the one from that zip, ignore the classdata-uabe.tpk file)

Ill check that out thank you for sharing.

**Comment by Igor55x** [comment]
> Try to see if this will work. It's made for `2018.4.10f1` so it could be outdated but it's worth a shot. https://github.com/nesrak1/AssetsTools.NET/files/5139741/classdata-U2018.4.10f1.zip (replace the classdata.tpk file by uabe with the one from that zip, ignore the classdata-uabe.tpk file)

Hi. I tested the `classdata.tpk` and this is what happened:
It doesn't work properly ☹

**1) An error message appears (multiple times):**
![err_1](https://user-images.githubusercontent.com/74247502/105846583-71703900-5fed-11eb-853f-9605beb06448.png)

**2) All asset data is empty (dump export was also unsuccessful):**
![err_2](https://user-images.githubusercontent.com/74247502/105846657-8a78ea00-5fed-11eb-9ebf-c1950c732737.png)

# I hope you can fix it 🤔

**Comment by Igor55x** [comment]
So, I have the dump that is **100%** correct. You can download the dump file here: [link](https://github.com/DerPopo/UABE/files/6260877/PlayerSettings.txt).
Thanks also to _[nesrak1](https://github.com/nesrak1)_ for updating the [classdata.tpk](https://github.com/DerPopo/UABE/files/6221297/classdata.zip) file.
