### ISSUE TITLE
UnityFS file (5.x.x 2019.4.14f1) "This file isn't a valid assets file!" error... 

### ISSUE THREAD

**Issue by BoomBookTR** [SeriousCache/UABE#398]
![image](https://user-images.githubusercontent.com/10184695/106377125-cc1de200-63ab-11eb-9c7c-b41a0c9f5600.png)
![image](https://user-images.githubusercontent.com/10184695/106378618-60da0d00-63b7-11eb-86b4-a27b6365c964.png)

[locale.zip](https://github.com/DerPopo/UABE/files/5899312/locale.zip)

what can i do? there is files in zip archive.
I think this is new UnityFS file.
I found previous version like this...
i can find files there.
Need UABE update for this files.
Ty...

**Comment by orangespoons** [comment]
https://file.io/hEmrhwXFNFa0
.144 files are probably script files.
However, the eset may be protected.

https://gall.dcinside.com/mgallery/board/view/?id=spiceandwolf&no=22744&page=1
Please refer to this page. :)

**Comment by BoomBookTR** [comment]
no support?

**Comment by mskgroup** [comment]
[Here solved your problem#410](https://github.com/DerPopo/UABE/issues/410)
