### ISSUE TITLE
Not working with new versions

### ISSUE THREAD

**Issue by Ason177** [SeriousCache/UABE#400]
Please make it work with 2019 and 2020 unitygames. plllsssss

**Comment by Ason177** [comment]
Super important

**Comment by NBAPJ** [comment]
Is anyone working on updating it?

**Comment by BoomBookTR** [comment]
waiting update...!

**Comment by philou-felin** [comment]
Yes... Someone could fork it or update this repo.

**Comment by mskgroup** [comment]
[Here solved your problem](https://github.com/DerPopo/UABE/issues/410)
