### ISSUE TITLE
Unable to read the bundle file! (Invalid file or unknown version?)

### ISSUE THREAD

**Issue by Only-a-cat** [SeriousCache/UABE#411]
Does anyone know how to resolve the error "Unable to read the bundle file! (Invalid file or unknown version?)" from Assets Bundle Extractor ..this came to me when I updated a game to the latest version, and I don't know how to resolve itt

**Comment by Woodi-dev** [comment]
Same problem with Among Us... I guess version incompatibility

**Comment by Only-a-cat** [comment]
yes, i was also talking about among us

**Comment by Woodi-dev** [comment]
you can extract sprites with AssetStudio but you cannot modify them. Im waiting for UABE to update

**Comment by Only-a-cat** [comment]
where do I download the asset studio?

**Comment by Woodi-dev** [comment]
https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts

**Comment by Only-a-cat** [comment]
is giving a very big error, I can't copy
;____________________; do you have discord?

**Comment by washingleavesandthensome23-434** [comment]
yep , wanted to modify Narita Boy to support 4k , yet nothing it keeps on resetting its registry keys once game starts , so i recon i gotta modify globalgamemanagers, extractor dont support most recent Unity tho , help

**Comment by mskgroup** [comment]
[Here solved your problem#410](https://github.com/DerPopo/UABE/issues/410)

**Comment by Intharth** [comment]
> [Here solved your problem#410](https://github.com/DerPopo/UABE/issues/410)

except you havn't for me - my game is 2020.3 :)

**Comment by toastchest** [comment]
ummm how do i dowload it i downloaded the code but it was not what i was looking for. could someone help?

**Comment by tonadota** [comment]
I know the solution.
There is UAAE(Unity Assets Advanced Editor,  Upward compatible with UABE（UABEの上位互換）). 
https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q12245192492
the answer of above page has the URL to downloading page
