### ISSUE TITLE
v2020.2.6.9052483 support?

### ISSUE THREAD

**Issue by AToska21** [SeriousCache/UABE#415]
Yeah, sorry for the overly specific title. Among Us was updated to this version of unity. Without support for it, I cannot edit the sharedassets. Am I doing something wrong? I used the Options > Edit Type Package.

Thanks! -
@AToska21

**Comment by mskgroup** [comment]
[Here solved your problem#410](https://github.com/DerPopo/UABE/issues/410)

**Comment by AToska21** [comment]
Didn't work, When I tried Edit Type Package v2020.2.6 didn't appear.

**Comment by AToska21** [comment]
Update: I tried replacing classdata.tpk in the root folder, did nothing.

**Comment by StealthyPony** [comment]
Can confirm, it doesn't work

**Comment by Igor55x** [comment]
> Update: I tried replacing classdata.tpk in the root folder, did nothing.

Try this [`classdata.tpk`](https://github.com/Igor55x/UAAE/files/6682534/classdata.zip) file.

**Comment by StealthyPony** [comment]
> > Update: I tried replacing classdata.tpk in the root folder, did nothing.
> 
> Try this [`classdata.tpk`](https://github.com/Igor55x/UAAE/files/6682534/classdata.zip) file.

Unfortunately that file does not have 2020.2.6, from the 2020 versions it does have 1.6, 2.2 and 3.12
