### ISSUE TITLE
2020 and 2021 unity support

### ISSUE THREAD

**Issue by ELECTROTIBIYT** [SeriousCache/UABE#421]
there is no support for the 2020 and 2021 versions of unity and an update for that would be REALY usefull this is a great program and i have used it for my texture packs for unity games but now those have been updated to a newer version of unity that isnt supported

**Comment by A-nonymous027** [comment]
#392

**Comment by A-nonymous027** [comment]
There's a new UABE (#410), but it's still in progress.

**Comment by Igor55x** [comment]
> there is no support for the 2020 and 2021 versions of unity and an update for that would be REALY usefull this is a great program and i have used it for my texture packs for unity games but now those have been updated to a newer version of unity that isnt supported

Try this [`classdata.tpk`](https://github.com/Igor55x/UAAE/files/6682534/classdata.zip) file.
