### ISSUE TITLE
UABE Can't open bundle (inavlid file or unknown version)

### ISSUE THREAD

**Issue by PizzaMosnterr** [SeriousCache/UABE#423]
I am trying to make a custom hat in among us but when I try to use UABE and error message comes up and says:"Can't open bundle (inavlid file or unknown version)" I tried both 32Bit and 64Bit and in both I got the same error. Thanks for the help anyways.

**Comment by IgnitedBread** [comment]
Dude same, but I'm trying to make a custom mask and make a custom skin. I'm trying to make John Roblox in among us but the error always gets me. This is extremely annoying but that's life ya know. We just gotta be patient for the dev to fix those bugs.

**Comment by iWalk809** [comment]
SOMEONE HELP US

**Comment by LoganPlayzUsezGitHub** [comment]
same
