### ISSUE TITLE
Unable to decompress bundle file error on a non-encrypted file

### ISSUE THREAD

**Issue by teslabyte** [SeriousCache/UABE#424]
Unity version : 2018.4.23f1
Files are from a mobile game called Punishing Gray Raven. Looking at them through Hex/Notepad++ they don't look encrypted and they don't have a double header( Like some Netmarble games do). AssetStudioGui doesn't open them, and UABE gives the "Unable to decompress bundle file" error.
Here's an example of one asset file, since the game is well over 5Gb.
[asset_example.zip](https://github.com/DerPopo/UABE/files/6492457/asset_example.zip)

**Comment by anhkyt122** [comment]
I am also having this problem...

**Comment by BTRbatam** [comment]
may i get the file from the game? or the pgr unity asset bunde
