### ISSUE TITLE
UABE is deprecated, use UAAE

### ISSUE THREAD

**Issue by Igor55x** [SeriousCache/UABE#427]
[Link](https://github.com/Igor55x/UAAE)

**Comment by webfischi** [comment]
UABE was long without knock offs, and now there is UABEA and UAAE can't you join forces, so we don't get two unfinished enviroments for a long time?

**Comment by grepwood** [comment]
@webfischi talk to the devs of these 2 projects. Maybe they can figure out how they can co-operate on a superior common solution?

**Comment by JEmlay** [comment]
Looks like they both only support textures.  That's a far cry from anything that's actually usable.
