### ISSUE TITLE
Error UABE "Unable to read the bundle file! (Invalid file or unknown version?)"

### ISSUE THREAD

**Issue by MicaTails2009** [SeriousCache/UABE#429]
I can't load package files, you can help me? (pls ._.)

**Comment by Bloxbug** [comment]
i have that same issue but i cant figure out why

**Comment by gupie408** [comment]
https://github.com/Igor55x/UAAE/releases/tag/v1

**Comment by Igor55x** [comment]
> https://github.com/Igor55x/UAAE/releases/tag/v1

Use the latest version: [link](https://github.com/Igor55x/UAAE/releases/tag/v2).

**Comment by raDiesle** [comment]
Hey I tried latest version v2. It works to open file, but when I click "Info", it stops working




************** Ausnahmetext **************
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at AssetsTools.NET.AssetsFileReader.ReadInt32()
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeInstance..ctor(AssetTypeTemplateField[] baseFields, AssetsFileReader reader, Int64 filePos)
   at AssetsTools.NET.AssetTypeInstance..ctor(AssetTypeTemplateField baseField, AssetsFileReader reader, Int64 filePos)
   at AssetsAdvancedEditor.Assets.AssetsWorkspace.MakeAssetContainer(AssetItem item, Boolean forceFromCldb) in C:\Users\Lenovo\source\repos\AssetsAdvancedEditor\AssetsAdvancedEditor\Assets\AssetsWorkspace.cs:line 130
   at AssetsAdvancedEditor.Winforms.AssetsViewer.AddAssetItem(AssetsFileInstance fileInst, AssetFileInfoEx info, Int32 fileId) in C:\Users\Lenovo\source\repos\AssetsAdvancedEditor\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 156
   at AssetsAdvancedEditor.Winforms.AssetsViewer.LoadAssetsToList() in C:\Users\Lenovo\source\repos\AssetsAdvancedEditor\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 74
   at AssetsAdvancedEditor.Winforms.AssetsViewer..ctor(AssetsManager am, AssetsFileInstance instance, Boolean fromBundle) in C:\Users\Lenovo\source\repos\AssetsAdvancedEditor\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 63
   at AssetsAdvancedEditor.Winforms.Menu.btnInfo_Click(Object sender, EventArgs e) in C:\Users\Lenovo\source\repos\AssetsAdvancedEditor\AssetsAdvancedEditor\Winforms\Menu.cs:line 300
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Geladene Assemblys **************
System.Private.CoreLib
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Private.CoreLib.dll.
----------------------------------------
AssetsAdvancedEditor
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/raDiesle/Downloads/UAAE-rel2-win/UAAE/AssetsAdvancedEditor.dll.
----------------------------------------
System.Runtime
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Runtime.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 5.0.13.0.
    Win32-Version: 5.0.1321.56701.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.13/System.Windows.Forms.dll.
----------------------------------------
System.Windows.Forms.Primitives
    Assembly-Version: 5.0.13.0.
    Win32-Version: 5.0.1321.56701.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.13/System.Windows.Forms.Primitives.dll.
----------------------------------------
System.ComponentModel.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.ComponentModel.Primitives.dll.
----------------------------------------
System.Runtime.InteropServices
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Runtime.InteropServices.dll.
----------------------------------------
System.Drawing.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Drawing.Primitives.dll.
----------------------------------------
System.Collections.Specialized
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Collections.Specialized.dll.
----------------------------------------
System.Console
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Console.dll.
----------------------------------------
System.Drawing.Common
    Assembly-Version: 5.0.0.2.
    Win32-Version: 5.0.1221.52207.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.13/System.Drawing.Common.dll.
----------------------------------------
System.Threading
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Threading.dll.
----------------------------------------
System.Diagnostics.TraceSource
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Diagnostics.TraceSource.dll.
----------------------------------------
System.Collections
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Collections.dll.
----------------------------------------
AssetsTools.NET
    Assembly-Version: 2.0.0.0.
    Win32-Version: 2.0.0.0.
    CodeBase: file:///C:/Users/raDiesle/Downloads/UAAE-rel2-win/UAAE/AssetsTools.NET.dll.
----------------------------------------
netstandard
    Assembly-Version: 2.1.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/netstandard.dll.
----------------------------------------
Microsoft.Win32.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/Microsoft.Win32.Primitives.dll.
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.ComponentModel.EventBasedAsync.dll.
----------------------------------------
System.Threading.Thread
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Threading.Thread.dll.
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: 5.0.1321.56701.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.13/Accessibility.dll.
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.ComponentModel.TypeConverter.dll.
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.20.51904.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.13/Microsoft.Win32.SystemEvents.dll.
----------------------------------------
System.Collections.Concurrent
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Collections.Concurrent.dll.
----------------------------------------
System.Runtime.Extensions
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Runtime.Extensions.dll.
----------------------------------------
System.ComponentModel
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.ComponentModel.dll.
----------------------------------------
System.Memory
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Memory.dll.
----------------------------------------
System.Buffers
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Buffers.dll.
----------------------------------------
System.Resources.Extensions
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.20.51904.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.13/System.Resources.Extensions.dll.
----------------------------------------
System.ObjectModel
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.ObjectModel.dll.
----------------------------------------
System.Linq
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Linq.dll.
----------------------------------------
System.Collections.NonGeneric
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Collections.NonGeneric.dll.
----------------------------------------
System.IO.FileSystem
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.IO.FileSystem.dll.
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Runtime.CompilerServices.Unsafe.dll.
----------------------------------------
System.Text.RegularExpressions
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Text.RegularExpressions.dll.
----------------------------------------
System.Threading.ThreadPool
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Threading.ThreadPool.dll.
----------------------------------------
System.Private.Uri
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Private.Uri.dll.
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Runtime.Serialization.Formatters.dll.
----------------------------------------
Mono.Cecil
    Assembly-Version: 0.11.3.0.
    Win32-Version: 0.11.3.0.
    CodeBase: file:///C:/Users/raDiesle/Downloads/UAAE-rel2-win/UAAE/Mono.Cecil.dll.
----------------------------------------
Texture
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/raDiesle/Downloads/UAAE-rel2-win/UAAE/Plugins/Texture.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 5.0.13.0.
    Win32-Version: 5.0.1321.56701.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.13/de/System.Windows.Forms.resources.dll.
----------------------------------------
System.Diagnostics.StackTrace
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Diagnostics.StackTrace.dll.
----------------------------------------
System.Reflection.Metadata
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Reflection.Metadata.dll.
----------------------------------------
System.Collections.Immutable
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Collections.Immutable.dll.
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.IO.MemoryMappedFiles.dll.
----------------------------------------
System.IO.Compression
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.IO.Compression.dll.
----------------------------------------
System.Text.Encoding.Extensions
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Text.Encoding.Extensions.dll.
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1321.56516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Diagnostics.FileVersionInfo.dll.
----------------------------------------

************** JIT-Debuggen **************
