### ISSUE TITLE
MovieTexture export does nothing

### ISSUE THREAD

**Issue by Nintynuts** [SeriousCache/UABE#455]
Selected a MovieTexture asset, clicked on 'Plugins', double clicked 'Export to .ogv' and nothing happens, no error or hint of what might have gone wrong.

**Comment by Nintynuts** [comment]
Was this fixed?

**Comment by SeriousCache** [comment]
I haven't ported (i.e. largely rewritten) the MovieTexture plugin to the new version yet.
However, it appears like MovieTextures no longer contain the video data in recent Unity builds. Maybe what you are looking for is in a VideoClip asset. For now, you can export/import VideoClips through the View Data option (right click on the resource), you may need to guess the right file extension, though.

**Comment by Nintynuts** [comment]
The game I was trying to export from seemed to have the video data within the MovieTexture based on the indicated size, but it was an older version of unity. Is there a different task I can subscribe to to see updates on this issue?
