### ISSUE TITLE
Unity 2019.4 support? Escape From Tarkov

### ISSUE THREAD

**Issue by jons** [SeriousCache/UABE#456]
hey, requesting an update to support the latest file format (i think) in order to extract voicelines from an asset bundle in escape from tarkov (EFT) . i doubt the bundle format has changed, it's probably just the header.

for the file i would like to extract, it appears the bundle header declares version `2019.4.32f1` or a substring thereof:
```
jon@stray:~$ hexdump -C /mnt/c/home/stream/eft-bear/bear_1_voice.bundle | head -n 4
00000000  55 6e 69 74 79 46 53 00  00 00 00 07 35 2e 78 2e  |UnityFS.....5.x.|
00000010  78 00 32 30 31 39 2e 34  2e 33 32 66 31 00 00 00  |x.2019.4.32f1...|
00000020  00 00 00 02 b4 8b 00 00  00 5b 00 00 00 9d 00 00  |.........[......|
00000030  00 43 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |.C..............|
```

for those looking for it, the files come from path\to\tarkov\EscapeFromTarkov_Data\StreamingAssets\Windows\assets\content\audio\phrases

**Comment by Syfity** [comment]
[UnityFS 5.x.x.2019.4.4f1] also needs an update

**Comment by woctezuma** [comment]
Try https://github.com/AssetRipper/AssetRipper
