### ISSUE TITLE
Note: Closed issues pre-3.0

### ISSUE THREAD

**Issue by SeriousCache** [SeriousCache/UABE#470]
I closed most older issues that may no longer apply to 3.0.
If you think an issue still applies to the latest release, feel free to write a comment in that issue or open a new one.
Thanks!

**Comment by rowanbean1960** [comment]
@SeriousCache  I love the new layout and click on the value to change it btw, but I need help.
When extracting monobehaviour, it says class information needs to be extracted to show the complete asset data,
then it wants me to open allot of dll files I don't have. What do I do to get the complete asset data?
Is there a way to get the complete asset data without needing to open all those dlls?

**Comment by SeriousCache** [comment]
The game probably uses il2cpp and thus is missing the dlls in the Managed folder.
There appears to be a tool to generate 'skeleton' dlls from the il2cpp data, but I haven't tested it: https://github.com/Perfare/Il2CppDumper

I'll close this here, please open a new issue if you have further questions.
