### ISSUE TITLE
Running on Mac OS？

### ISSUE THREAD

**Issue by liang530** [SeriousCache/UABE#477]
Running on Mac OS？

**Comment by SeriousCache** [comment]
It may work through [Wine](https://wiki.winehq.org/MacOS#Installing_Wine_packages_using_homebrew), but I can't test it myself.

**Comment by SeriousCache** [comment]
Closing this, as even if it didn't work through Wine on MacOS, I don't have a proper way of testing it and wouldn't know whatever changes are necessary to make it work.
