### ISSUE TITLE
Hello, I would like to ask how to build UABE 3.0? 

### ISSUE THREAD

**Issue by mskgroup** [SeriousCache/UABE#480]
Hello, I would like to ask how to build UABE 3.0? When I build, cmake prompts me "not found RT" and "not found pkg_config"

**Comment by mskgroup** [comment]
I tried for a long time, but neither library could be found

**Comment by SeriousCache** [comment]
I built it through the Visual Studio 2022 GUI without any special configuration; as mentioned in the Readme, you can remove the add_subdirectory lines for TexToolWrap and Plugins/AudioClip, though that does not appear to be the reason for these errors.

I can't rule out that it automatically finds some library on my system, so please report back if you did use VS 2022.

**Comment by mskgroup** [comment]
yes, i use VS 2022

I downloaded and installed FMOD and PVRTexTool, how do I include them in my project?

**Comment by mskgroup** [comment]
i remove the add_subdirectory lines for TexToolWrap and Plugins/AudioClip, but VS2022 still have error :

1、
CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.22/Modules/FetchContent.cmake:1087 (message):
  Build step for astcenc failed: 1	CrossCompileExample	C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.22/Modules/FetchContent.cmake	1087	

2、
CMake Error at D:/Users/Pozet/Downloads/UABE-master/out/build/x64-Debug/_deps/astcenc-subbuild/astcenc-populate-prefix/tmp/astcenc-populate-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://github.com/ARM-software/astc-encoder'


FAILED: astcenc-populate-prefix/src/astcenc-populate-stamp/astcenc-populate-download D:/Users/Pozet/Downloads/UABE-master/out/build/x64-Debug/_deps/astcenc-subbuild/astcenc-populate-prefix/src/astcenc-populate-stamp/astcenc-populate-download 
cmd.exe /C "cd /D D:\Users\Pozet\Downloads\UABE-master\fetchcontent && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -P D:/Users/Pozet/Downloads/UABE-master/out/build/x64-Debug/_deps/astcenc-subbuild/astcenc-populate-prefix/tmp/astcenc-populate-gitclone.cmake && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E touch D:/Users/Pozet/Downloads/UABE-master/out/build/x64-Debug/_deps/astcenc-subbuild/astcenc-populate-prefix/src/astcenc-populate-stamp/astcenc-populate-download"
ninja: build stopped: subcommand failed.		D:/Users/Pozet/Downloads/UABE-master/out/build/x64-Debug/_deps/astcenc-subbuild/astcenc-populate-prefix/tmp/astcenc-populate-gitclone.cmake	31

**Comment by SeriousCache** [comment]
Also you can take a look at [CMakeSettings.Example.json](https://github.com/SeriousCache/UABE/blob/master/CMakeSettings.Example.json), which also shows how the paths of FMOD and PVRTexTool can be supplied (caveat: I am not sure if the expected subdirectory structure matches a regular installation -  see the CMakeModules directory if you want to know which files it looks for).

**Comment by mskgroup** [comment]
I set PVRTexTool_ROOT and FMOD_ROOT, and also set CMakeModules, but VS can't find this dependency

**Comment by mskgroup** [comment]
[CMakeSettings.Example.zip](https://github.com/SeriousCache/UABE/files/8644120/CMakeSettings.Example.zip)

**Comment by mskgroup** [comment]
![屏幕截图 2022-05-07 082807](https://user-images.githubusercontent.com/51709279/167230537-216f9d33-9012-49d3-b3d1-3c79483d5ca4.png)
![屏幕截图 2022-05-07 082834](https://user-images.githubusercontent.com/51709279/167230538-03d6de33-294c-47f5-9229-cf4d771fb291.png)

**Comment by mskgroup** [comment]
I made it! thank you very much
