### ISSUE TITLE
Chrome & Edge detects virus when downloading UABE 3.0 beta 1

### ISSUE THREAD

**Issue by 1030** [SeriousCache/UABE#481]
As in the title, I can't get a browser to download the release as it's convinced it contains a virus.

Thanks
J

**Comment by BarnMTB** [comment]
[VirusTotal Scan Result](https://www.virustotal.com/gui/file/803384cfd183884a81fbb077d109b76c9a1dddbe512e4398988c8de81ca270a2?nocache=1):

![image](https://user-images.githubusercontent.com/16902530/166148006-dc1b661a-13a1-4485-9a5f-3729ae127e3c.png)

**Comment by SeriousCache** [comment]
Closing this, since TypeTreeGenerator appears to be the file which Windows Defender appears to have personal issues with (issue #479).
