### ISSUE TITLE
Aba Unity Files (Pokemon Home)

### ISSUE THREAD

**Issue by Escope12** [SeriousCache/UABE#484]
HI guys. I got these .aba files from Pokemon Home but I don't know how to open them. Is it possible to add support for them?

[Files.zip](https://github.com/SeriousCache/UABE/files/8644170/Files.zip)

**Comment by SeriousCache** [comment]
Those files apparently have some kind of custom obfuscation/encryption at the beginning, which is outside the scope of UABE.  
I guess it's some sort of block based encryption. The first 32 bytes are identical across two different files (which is where the engine version strings should be) but the following ones are all different.  
Getting any further will take some reverse engineering (quickly getting you into less than perfectly legal territory).
