### ISSUE TITLE
Apply EMIP using command line with the new release

### ISSUE THREAD

**Issue by ibaios** [SeriousCache/UABE#494]
Hi,

I used DerPopo's UABE to generate EMIP files and then apply the changes using the command line (executed from an installer program).

I've tried to do the same with this release and it didn't work, and it just opens the application.

Is this command line feature removed?
Will you readd this feature? Is there any alternative way to do this?

Thanks in advance!

**Comment by mskgroup** [comment]
#472

**Comment by ibaios** [comment]
Ok, I saw that but I misread. So, if I've understand it well, it could be added in the future, but it cannot be used at the moment.

Thank you!
