### ISSUE TITLE
there is a virus

### ISSUE THREAD

**Issue by video-tootarolls00** [SeriousCache/UABE#501]
windows defender keeps getting triggered

**Comment by ithinkandicode** [comment]
Came here to report this. VirusTotal reports a lot of detections from multiple services:

<img width="581" alt="VirusTotal" src="https://user-images.githubusercontent.com/43499897/168491624-9adc6cc8-fef4-4eec-b760-0c6db3e981a9.png">

https://www.virustotal.com/gui/file/803384cfd183884a81fbb077d109b76c9a1dddbe512e4398988c8de81ca270a2

**Comment by SeriousCache** [comment]
There is definitely not a virus, just lots of annoying scanners going after the one trivially scannable .NET file. 
Closing this (duplicate of #479 )
