### ISSUE TITLE
Unknown sign 

### ISSUE THREAD

**Issue by DogancanYr** [SeriousCache/UABE#512]
![Screenshot 2022-05-24 210224](https://user-images.githubusercontent.com/90002969/170102276-ff7004d9-412a-4f78-a9f2-7d9d84c84c79.png)
Unknown sign , I take it from another place, no such problem.

**Comment by SeriousCache** [comment]
If that's a TextAsset, export/import the text file using the Plugins button.  
Export Raw will have additional stuff at the beginning that notepad cannot render properly.

**Comment by DogancanYr** [comment]
Sorry, I should have clicked on it and hit the button .Really nice software.
