### ISSUE TITLE
Need help while modifying meshes

### ISSUE THREAD

**Issue by Dani-error** [SeriousCache/UABE#543]
I exported a mesh from a game as .obj, next I changed it with blender, exported as .obj added to unity (the same version as the game), compiled, opened UABE, exported as json, added its bones. Then I opened UABE but with the game files, imported the dump, and when I run the game, shows invisible.

**Comment by Dani-error** [comment]
Fixed!

**Comment by Pidar1234** [comment]
> Fixed!

Could you tell us how you solved this problem?

**Comment by Dani-error** [comment]
Well its was a problem with my mesh, it was empty... So I tried with another mesh and it worked!
