### ISSUE TITLE
Won't even open

### ISSUE THREAD

**Issue by PeckNeck123** [SeriousCache/UABE#544]
When I try to open it, I get this series of messages. How do I fix it?
![image](https://user-images.githubusercontent.com/86134314/178009744-7bc71ec4-9c08-4e45-81fc-112ca150292e.png)
![image](https://user-images.githubusercontent.com/86134314/178009780-c3c9a587-81dc-4579-b04d-ca75c87c4e34.png)
![image](https://user-images.githubusercontent.com/86134314/178009814-8af09b80-48b5-4b8e-9414-151503060e6d.png)
![image](https://user-images.githubusercontent.com/86134314/178009857-a8a9a11b-066c-4c17-8f92-7c8d0e2c4c31.png)

**Comment by shawnmcla** [comment]
Do you have MSVC Redistributable installed on your machine? It doesn't seem like it.

**Comment by PeckNeck123** [comment]
> Do you have MSVC Redistributable installed on your machine? It doesn't seem like it.

do I install ARM64, x86, or x64?
