### ISSUE TITLE
Can't build due to a C7595 error

### ISSUE THREAD

**Issue by jbpotpot** [SeriousCache/UABE#551]
Hi, thanks for the efforts in making this tool.
I'm currently trying to use the newest version and am unsuccesful at building in Visual Studio 2022. I have an error code C7595: call to immediate function is not a constant expression on line 686 of the file AssetPluginUtil.cpp in folder UABE_Generic. Has anyone else resolved this issue and how? Thanks in advance for your assistance

**Comment by trong8820** [comment]
Try std::vformat_to(std::back_inserter(lineBuf), "\\u{:04u}", std::make_format_args(strValue[i]));

**Comment by jbpotpot** [comment]
It worked on that specific line and i could adapt it for the other troublesome lines, thanks a lot!
