### ISSUE TITLE
Is there any way to modify the VideoClip?

### ISSUE THREAD

**Issue by Kafu-Yukimura** [SeriousCache/UABE#552]
Texture2D provides a plug-in for editing, but VideoClip does not have a plugin, so it is difficult to edit.
I would like to know how to modify it or if there is room for improvement.

**Comment by LukeSaward1** [comment]
VideoClips are not supported. If you mean AudioClips, then it's not directly supported yet.

**Comment by Kafu-Yukimura** [comment]
Yes, I was talking about VideoClips.
I wanted to edit the OP/ED of the game with a video with subtitles, but there is no way.

**Comment by Kafu-Yukimura** [comment]
#549 link https://youtu.be/5rk8bj7uvws confirmed that VideoClips is also applied in addition to AudioClips.
I was able to apply this as a temporary measure. But i still hope to be supported by the UABE in the future.
