### ISSUE TITLE
Win32.MalwareX-gen [Trj] infected! 

### ISSUE THREAD

**Issue by fonko** [SeriousCache/UABE#554]
i was about to install this and i got this alert from my antivirus

![image](https://user-images.githubusercontent.com/2717577/180650947-0b2170d2-d60a-4e8b-94a8-02fda3bee7e7.png)

**Comment by thouhodied** [comment]
Yeah, VirusTotal has like... 30 alerts for the software too

**Comment by SeriousCache** [comment]
#479
