### ISSUE TITLE
3.0beta1_32bit is fine, 64bit gets deleted on a virus

### ISSUE THREAD

**Issue by JayQ2K** [SeriousCache/UABE#558]
Downloading 64bit first the virusscanner immediately went of about a virus and deleted the file. The 32bit version doesn't have this problem and downloads correctly. Can this be checked for the upcoming release?

It is called "Trojan:AndroidOS/ZkarletFlash"

**Comment by ABalinko** [comment]
I have this problem too :(

**Comment by DJPlaya** [comment]
TypeTreeGenerator.exe is the culprid. Strangely it also hits up my Sophos even if it dosent say so on report
https://www.virustotal.com/gui/file/423f6774b299fad62d4f879a39671fc5c13c3245b682b647ed02cc568e1029a6

**Comment by SeriousCache** [comment]
#479
