### ISSUE TITLE
Windows defender the doo doo fart clown thinks this is a virus,

### ISSUE THREAD

**Issue by juanroman74454811** [SeriousCache/UABE#563]
Im trying to mod Baldis Basics, i downloaded a copy but both my RAR and ZIP extractor and Windows Defender thinked its a virus, i downloaded the 32 bit one,

**Comment by juanroman74454811** [comment]
Im actually angry about this, Maybe microsoft is a doodoo fart molester to me,
I would reccomend using an computer without an antivirus,

**Comment by graytFox** [comment]
"doo doo fart clown" is the best thing I've heard all day thank you

**Comment by froid-san** [comment]
Glad I'm not the only one having a problem because of this doo doo fart clown

**Comment by SeriousCache** [comment]
#479
