### ISSUE TITLE
UABE closes/crashes after editing Texture2D file

### ISSUE THREAD

**Issue by kotobdev** [SeriousCache/UABE#566]
After attempting to use the Edit plugin to replace the texture on a Texture2D asset, UABE closes almost instantly, and fails to change anything. I don't think UABE generates crash logs, so I have no idea what could be causing this. These are the settings that I'm using.
![image](https://user-images.githubusercontent.com/59124164/184451298-3d55c200-9259-49eb-a82b-67706cbfc594.png)

Versions Affected: 3.0 Beta 32bit, 3.0 Beta 64bit

**Comment by Krystedez** [comment]
Hi there. It works fine if you change the "Texture format" second from top using the drop down menu. Select "DTX1".  The guide at https://docs.google.com/document/d/114RA-79AUCc9ShCKtNmTkrTW8gxlOmAlFxmeFf3wqa4/edit#
will tell you only that it WILL change it to that texture, but misses that step to change the format if it's not default to it from using for the first time.

Hope that works, I had the same exact issue myself and had to re-read the guide a little to guess.  
![image](https://user-images.githubusercontent.com/6722739/184556474-5e34ba3b-02dc-4ac2-8a09-6159e4432bdf.png)
![image](https://user-images.githubusercontent.com/6722739/184556525-e6e47562-8a05-4ab7-bede-74e7aea15a35.png)

**Comment by kotobdev** [comment]
Thanks! That seemed to work.
