### ISSUE TITLE
Newest version downloads a virus

### ISSUE THREAD

**Issue by VirtualyMichael** [SeriousCache/UABE#567]

**Comment by lolraceHun** [comment]
![image](https://user-images.githubusercontent.com/40703369/184539424-e13b3b8a-d963-4689-9301-7f6a1f30e96b.png)
Windows defender detecting a virus

**Comment by timur-losev** [comment]
Virus total reports a virus WTF??

**Comment by timur-losev** [comment]
![изображение](https://user-images.githubusercontent.com/2165138/184547207-aa8b9e1a-2d42-4ddc-986d-17c968f3a37e.png)

**Comment by VirtualyMichael** [comment]
Do not install it cloud installs a virus that is really nasty

**Comment by timur-losev** [comment]
Tools folder is SUSS
![изображение](https://user-images.githubusercontent.com/2165138/184547957-5c30f3db-c14d-43a9-ab7c-e8759c40840a.png)

**Comment by pascaltozzi** [comment]
Please report it on: https://support.github.com/contact/report-abuse?category=report-abuse&report=other&report_type=unspecified

**Comment by araghon007** [comment]
Now how did that happen..
Seems this commit modified TypeTreeGenerator.exe
https://github.com/SeriousCache/UABE/commit/78ee37ef5da83a2eec607fb7a3f3ab16731c19e4

Guess this is why you should never share binaries on here ¯\_(ツ)_/¯

**Comment by LukeSaward1** [comment]
It is not a virus.

**Comment by SeriousCache** [comment]
#479
