### ISSUE TITLE
suggesstion

### ISSUE THREAD

**Issue by Kurainu** [SeriousCache/UABE#60]
can you make it compatible with linux

**Comment by DerPopo** [comment]
The UI is based on Win32 Dialogs and wouldn't be that easy to port to native X11 and Wayland or to existing cross-platform UI libraries. The best option seems to be using winelib, which greatly simplifies porting. I think most of the third party libraries I use should be compatible.
UABE works good with Wine itself, so for now I don't think it's that urgent.

**Comment by nesrak1** [comment]
How hard would it be to port the API to Linux? It doesn't use Win32 Dialogs.

**Comment by theonlyShiro** [comment]
I dont know how to use wine on linux i have a little raspberry with ubuntu mate and its not working there. Its have a differnt Architekture. And thats theproblem i think

**Comment by DerPopo** [comment]
Porting to ARM would likely cause issues with additional limitations to some things, such as data alignment. So far, the only thing you can do to run UABE is installing x86 Windows or Linux with Wine in an emulator such as qemu.

**Comment by rkevin-arch** [comment]
Any progress on at least a Linux API? Installing Wine just to automate some AssetBundle editing is quite clunky IMO. Thanks!

**Comment by nesrak1** [comment]
I don't know if he's working on Linux support, but if you're okay with using mono/core instead of wine, there's a c# version that's mostly the same as the c++ version: https://github.com/nesrak1/AssetsTools.NET

**Comment by rkevin-arch** [comment]
Thanks! I'll check it out. For now I've been using UnityPack (Python package), although it doesn't have write support so I had to cobble something dirty together that only works in really specific circumstances. I'll check out the C# API and see if I can make it work. Thanks!
