### ISSUE TITLE
Shared Assets?

### ISSUE THREAD

**Issue by TemporaryChan** [SeriousCache/UABE#610]
Is there a way to save a shared assets file in the same format that I opened it? After editing the shared assets file, I attempted to save it, but It saved it in a file format that wasn't the same as when I first opened it. It wouldn't let me change the file format either. It just said "FILE" instead of "ASSETS FILE." What could be the issue?

**Comment by UserIdklol** [comment]
just add it .assets

**Comment by TemporaryChan** [comment]
> just add it .assets

Thank you!
