### ISSUE TITLE
Can't open any assets file / Can't download version 3.0

### ISSUE THREAD

**Issue by Ravenika** [SeriousCache/UABE#631]
I am trying to mod a Unity game called "Baldi's Basics" and I can't seem to open the assets files with the UABE. It displays an error saying ""Unable to read the bundle file (Unknown version ?)". I tried it with another Unity game and it displays the same error.
I thought it was because I had the 2.2 version, but I can't seem to download the 3.3 version either.

Could someone help please ? It's been driving me mad.

Thank you !

**Comment by lostprophet** [comment]
1. Please add or link the files you are trying to open, so next time people don't have to go hunting on the internet for the game.
I just downloaded Baldi's Basics from itch.io (if that's what you are referring to), and for example, opened **resources.assets** without any issues with **UABE 3.0 beta 1**.
2. **I can't seem to download the 3.3 version** What do you mean by version 3.3 exactly? The latest is 3.0 beta 1, and perfectly downloadable from the very website, you are currently on.

**Comment by Ravenika** [comment]
Hold on, I've made a video of my two issues (and yes, I did mean 3.0 beta 1, I'm sorry).
https://youtu.be/5raRbwxR40c 
https://youtu.be/yag3V11obm0

**Comment by Ravenika** [comment]
Sorry for not leaving any files either. But I assure you I've been using the same application you have (except for the 3.0 version which I am unable to download).

**Comment by lostprophet** [comment]
> Sorry for not leaving any files either. But I assure you I've been using the same application you have (except for the 3.0 version which I am unable to download).

**First video:** I see Bitdefender is blocking the download, even the Bitdefender popup is there. A bunch of editors/extractors/repackers are identified as "malicious", however they are false positives. I'd suggest going in to Bitdefender's Quarantine or something, and whitelisting it.
**Second video:** I'm guessing the version you are using (seems to be version 2.2 from years ago) is too old to handle the new files of the game, so you'll need the new one.

**Comment by Ravenika** [comment]
It worked ! Bitdefender was the issue !
Thank you so much !

**Comment by lostprophet** [comment]
> It worked ! Bitdefender was the issue ! Thank you so much !

Glad it worked out. Happy modding!
