### ISSUE TITLE
Scene extracting

### ISSUE THREAD

**Issue by Gh0s7** [SeriousCache/UABE#77]
I've been playing with your tool and I tried loading a scene file (`level0`).

The tool correctly recognized scene's structure and I can't see all the objects inside it (with transforms, attached scripts and so on).

Given that Unity accepts YAML scenes ([example here](https://docs.unity3d.com/Manual/YAMLSceneExample.html)), can we have an "export scene" feature?

I tried looking up for source code to start working on this myself but I couldn't find it, so I thought that asking here could help.

**Comment by nesrak1** [comment]
I'm actually trying to do that right now.
I started working on something similar like this (in the API, I had a huge conversation about all the problems I was having #58.) But I ditched it because I did find a way to actually turn an assets file into an asset bundle and actually load that bundle into unity as a scene, but you have to either import in the dll (because unity notices you are missing scripts) or remove all of the scripts in the assets file. Only problem is with deleting the scripts is that if you have a large scene, it can take forever just to delete one asset (for me it was at least a minute before one script deleted).

**Comment by Gh0s7** [comment]
Do you have any source code that I can use to work on?

Also, since I have the DLLs, do you mind sharing how you did it?

**Comment by nesrak1** [comment]
Here's something I told someone a long time ago

Meanwhile, if you want to, you can turn an assets file into an unity3d file by using a weird version of disunity (It's pretty much the only thing it's able to do). It's in java so it'll run on any platform. https://drive.google.com/file/d/0B_w_cT4IsnDKbVFEWmtLUGVreFE/view?usp=sharing
This came from a steam guide:

> (Not sure if next step is necessary but I do it anyway)
> 17. Create a python script and paste this into it:
> ```
> import sys
> import hashlib
> 
> def md5(fname):
>     hash_md5 = hashlib.md5()
>     with open(fname, "rb") as f:
>         for chunk in iter(lambda: f.read(4096), b""):
>             hash_md5.update(chunk)
>     return hash_md5.hexdigest()
> 	
> print("CAB-" + md5(sys.argv[1]))
> raw_input("")
> ```
> 
> Now run it with python:
> `hasher.py "C:\Users\nesrak1\Downloads\Release\test.assets"`
> You should get an output that says something like CAB-xxx
> Rename the assets file with it (remove the assets extension also)
>
> 18. Create a new file called "createBundle.json" in the same folder of disunity and paste this:
> ```
> {
> 	"unityVersion":"5.x.x",
> 	"unityRevision":"5.1.1f1",
> 	"files":[CAB-xxxxxx],
> 	"compressed":false,"streamVersion":3
> }
> ```
> Also copy CAB-xxx into a new folder called "createBundle".
> 19. Type in cmd
> `disunity bundle-build createBundle.json -o .unity3d`

Pretty much, just get an md5 of the assets file and rename it CAB-md5 then create the json file, create new folder and run disunity on it.

https://docs.unity3d.com/Manual/LoadingAssetBundles.html is loading bundles and assets from them at runtime.

If the assets contains scripts, then unity won't load it saying how it doesn't have the right scripts. I know if you drag the game dll into Unity it will fix. You might be able to run the dll at runtime http://stackoverflow.com/a/18362459... but I'm not too sure.

**Comment by nesrak1** [comment]
There's a program called AssetVierwer that easily loads bundles: 

> For those of you who don't know, there's Unity Asset Vierwer, it let's you look at people's asset bundles and you can look at how they are done. (It's not going to let you steal their textures, etc)
> https://drive.google.com/file/d/0B_w_cT4IsnDKMHI0Ynl3RVBvd2M/view?usp=sharing is the link.
> Open it as a unity project and open LoadObject.cs. Inside you will see the line that says CreateFile.
> Copy the unity bundle you want (C:\Program Files (x86)\Steam\steamapps\workshop\content\304930) into the Assets folder in the project. You can replace the line With "Assets/bundlename.unity3d". Then just start the game in Unity and type the name of the game object (For guns, Item. Object, Model_0, etc...) into the textbox and press enter or click the button. Go back into the editor while the game is running and look to the left. Click on any of the objects that say clone and press f. Then you can look at how they are done.
> Note the position is going to be about 300y off of the original.

That was written for unturned... but it works in any game.

**Comment by nesrak1** [comment]
The thing is, I could probably easily write a script to turn this into a scene, but what wouldn't be easy would be actually trying to extract each and every asset to actually load into unity (animations... models [possible, but the current plugin right now exports as obj, and I don't think it has materialization support])

**Comment by Gh0s7** [comment]
Seems like it's not working, `AssetBundle assets = AssetBundle.LoadFromFile("Assets/level.unity3d");` in `LoadObjects` returns `null`.

Here's what I did:

- `python hasher.py level2`
- rename `level2` to `CAB-6659fe060a3fbaabd9569d65df88c2d3`
- created `createBundle.json` file and changed `CAB-xxxxxx` to `CAB-6659fe060a3fbaabd9569d65df88c2d3`
- create `createBundle` folder and copied `CAB-6659fe060a3fbaabd9569d65df88c2d3` into it
- `disunity bundle-build createBundle.json -o .unity3d`
- renamed `.unity3d` to `level.unity3d`
- copied `level.unity3d` into Assets folder of Asset Viewer
- changed `LoadObject` to load `Assets/level.unity3d`

Did I do something wrong?

**Comment by nesrak1** [comment]
What you did sounds right, But I've never used Unity above 5.3.5. Are you sure that your game is the right version too? You can tell if you open it up in notepad (ms one will lag to death)/hex editor and see at the top what the version is.
If it is the right version, it might actually be because of how old disunity is, in which case I don't know what to do.

**Comment by Gh0s7** [comment]
`5.3.3f1`

Do you think that downloading Unity 5.3.3f1 can help?

**Comment by nesrak1** [comment]
Yes. It probably will.

**Comment by Gh0s7** [comment]
```
The AssetBundle 'Assets/level.unity3d' could not be loaded because it references scripts that are not compatible with the currently loaded ones. Rebuild the AssetBundle to fix this error.
UnityEngine.AssetBundle:LoadFromFile(String)
<LoadCreateObjects>c__Iterator0:MoveNext() (at Assets/LoadObject.cs:31)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
LoadObject:LoadCreateObjectsInit(String) (at Assets/LoadObject.cs:21)
UnityEngine.EventSystems.EventSystem:Update()
```

We're getting closer to it.

Now, I've tried adding the dlls but Unity complains saying that

```
'Assets/Scripts/Assembly-CSharp/lib/Assembly-CSharp-firstpass.dll' shouldn't be queried by IsAssemblyCompatible, missing IsInternalOrCompiledAssembly check ?
UnityEditor.DockArea:OnGUI()
```

Using the code instead of the dlls doesn't seem to work either.
Any idea?

**Comment by nesrak1** [comment]
I'll see if I can write a program to remove the scripts from the assets file.

**Comment by nesrak1** [comment]
Bad news is I can't figure out how to batch delete MonoBehaviours :(

**Comment by iwanPlays** [comment]
UtinyRipper is able to extract scenes https://github.com/mafaca/UtinyRipper 

It worked with a 5.6 built game. I had to select all materials and set them to "Standard". Many textures could not be imported, no audio clips could be imported. The scene and all meshes were imported correctly as far as I can tell though.

**Comment by zorkind** [comment]
> UtinyRipper is able to extract scenes https://github.com/mafaca/UtinyRipper
> 
> It worked with a 5.6 built game. I had to select all materials and set them to "Standard" so they would not be pink "missing texture" type materials. Many textures could not be imported, no audio clips could be imported. The scene and all meshes were imported correctly as far as I can tell though.
> 
> Pressing the play button would crash Unity at first but removing some weird invisible objects helped.

I did that recently and it game me a scene alright, but he didn't kept the scripts attached or the values in the script properties, so it's a pain in the but to figure out what was in those slots :(

**Comment by fernandodarci** [comment]
Using DevXUnpacker Magic Studio helps a lot, at least I can see how are the scripts on scene
