### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by OmegaRogue** [SeriousCache/UABE#99]
Are there Plugins for extracting GameObjects and MonoBehaviours?

**Comment by DerPopo** [comment]
You can export a dump or the raw asset, I can't think of any other file formats to extract GameObjects or MonoBehaviours to. The extended type information of the MonoBehaviour specific to the script isn't stored in the .assets file (it is for bundles though) but the MonoBehaviour has a reference to a MonoScript where the assembly and the exact class name is described. With a .net or mono decompiler such as ILSpy or Telerik JustDecompile it's the same procedure as described here : https://github.com/DerPopo/UABE/issues/63
Note that some decompilers sort the fields alphabetically, while the fields in MonoBehaviours are stored in the order they are defined in the assembly. In case of ILSpy, the left class list has the fields sorted but the order in the decompilation view should be the correct one.

**Comment by OmegaRogue** [comment]
And also, can I add a MonoBehavior to a asset bundle?

**Comment by OmegaRogue** [comment]
And also, can I add a MonoBehavior to a asset bundle?

**Comment by DerPopo** [comment]
Only if the .assets file in the bundle already contains a MonoBehaviour of the same type. If that's the case, press File->Add in the Assets info window and fill the Type and Mono Class ID like it's filled in another MonoBehaviour of the same type. On the new asset, you can do anything you'd do with the existing MonoBehaviours.

**Comment by nkAlex** [comment]
Where can I look up this `Mono Class ID` value? I can only see the File and Type Ids in the interface.
